# Generated by Django 6.0 on 2025-12-17 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capteur",
            fields=[
                (
                    "id_capteur",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_capteur",
                    models.CharField(
                        choices=[
                            ("qualité_air", "Qualité Air"),
                            ("trafic", "Trafic"),
                            ("énergie", "Énergie"),
                            ("déchets", "Déchets"),
                            ("éclairage", "Éclairage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("en_maintenance", "En Maintenance"),
                            ("hors_service", "Hors Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quartier", models.CharField(default="Sousse", max_length=100)),
                ("date_installation", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Citoyen",
            fields=[
                (
                    "id_citoyen",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("score_ecologique", models.IntegerField(default=0)),
                (
                    "preferences_mobilite",
                    models.TextField(
                        help_text="Préférences de mobilité (JSON ou texte)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("statut", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Proprietaire",
            fields=[
                (
                    "id_proprietaire",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_proprietaire",
                    models.CharField(
                        choices=[("municipalité", "Municipalité"), ("privé", "Privé")],
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Technicien",
            fields=[
                (
                    "id_technicien",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("certification", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehiculeAutonome",
            fields=[
                (
                    "id_vehicule",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plaque_immatriculation",
                    models.CharField(max_length=20, unique=True),
                ),
                ("type_vehicule", models.CharField(max_length=50)),
                ("energie_utilisee", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id_intervention",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("prédictive", "Prédictive"),
                            ("corrective", "Corrective"),
                            ("curative", "Curative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duree", models.IntegerField(help_text="Durée en minutes")),
                ("cout", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "impact_co2",
                    models.DecimalField(
                        decimal_places=2, help_text="Impact CO2 en kg", max_digits=10
                    ),
                ),
                (
                    "capteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="api.capteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_participation", models.DateTimeField(auto_now_add=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.citoyen"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.consultation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="participants",
            field=models.ManyToManyField(through="api.Participation", to="api.citoyen"),
        ),
        migrations.AddField(
            model_name="capteur",
            name="proprietaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capteurs",
                to="api.proprietaire",
            ),
        ),
        migrations.CreateModel(
            name="InterventionTechnicien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("intervenant", "Intervenant"),
                            ("validateur", "Validateur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.intervention",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.technicien"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intervention",
            name="techniciens",
            field=models.ManyToManyField(
                through="api.InterventionTechnicien", to="api.technicien"
            ),
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id_trajet",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origine", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("duree", models.IntegerField(help_text="Durée en minutes")),
                ("economie_co2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets",
                        to="api.vehiculeautonome",
                    ),
                ),
            ],
        ),
    ]
