# Generated by Django 6.0.1 on 2026-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteur',
            options={'ordering': ['quartier', 'type_capteur', 'id_capteur']},
        ),
        migrations.AlterModelOptions(
            name='citoyen',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_debut', 'titre']},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-date_heure']},
        ),
        migrations.AlterModelOptions(
            name='interventiontechnicien',
            options={'ordering': ['intervention', 'role', 'technicien']},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['-date_participation']},
        ),
        migrations.AlterModelOptions(
            name='proprietaire',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='technicien',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['vehicule', 'origine', 'destination']},
        ),
        migrations.AlterModelOptions(
            name='vehiculeautonome',
            options={'ordering': ['plaque_immatriculation']},
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['quartier'], name='api_capteur_quartie_764367_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['statut'], name='api_capteur_statut_a4e741_idx'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['score_ecologique'], name='api_citoyen_score_e_b57c99_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['statut'], name='api_consult_statut_a9459c_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['type_intervention'], name='api_interve_type_in_8195b5_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['date_heure'], name='api_interve_date_he_7f47f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='interventiontechnicien',
            constraint=models.UniqueConstraint(fields=('intervention', 'technicien'), name='unique_technicien_per_intervention'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('citoyen', 'consultation'), name='unique_participation_per_consultation'),
        ),
    ]
